Project model
shescoding/projects-platform-backend pull request #10
Opened 2019-12-28 20:32 UTC by nurmerey

- [x] Created app scprojects and models inside it
- [x] Covers the fields from #5

Merge BLOCKED - needs #9 to be merged first.

2020-01-12 21:04 UTC, natsteinmetz requested changes

2020-01-12 21:04 UTC, natsteinmetz commented on scprojects/models.py
> +class Tag(models.Model):
We said we'd use an external tag library, so I would not create this model here. (#6 Add tag library)

2020-01-12 21:04 UTC, natsteinmetz commented on scprojects/models.py
> +    tech_stack = models.ManyToManyField(Tag)
We'd add this later, once we have integrated a tag library. So I'd remove it for now, together with the tag model.

2020-01-13 16:35 UTC, nurmerey commented on scprojects/models.py
> +class Tag(models.Model):
Yes, I remember that. This is intended to be a placeholder for the future Tag library. I am assuming it will be a Django Model as well?

2020-01-13 16:51 UTC, nurmerey commented on scprojects/models.py
> +    tech_stack = models.ManyToManyField(Tag)
Done

2020-01-13 16:52 UTC, nurmerey commented on scprojects/models.py
> +class Tag(models.Model):
I saw your other comment. Deleted the model.

2020-01-20 21:59 UTC, merged